### ISSUE TITLE
Database not being fully setup on install

### ISSUE THREAD

**Issue by jebentier** [tduniec/backstage-timesaver-plugin#5]
I'm currently trying to install this plugin in an existing Backstage instance, and it appears that the database isn't being fully configured properly.  This is the error that is coming out of the logs, which seems to indicate that one of the necessary tables was not created when the database was initialized.

```
[1] 2024-02-19T16:11:15.988Z backstage error Request failed with status 500 SELECT sum(time_saved), team, template_name from ts_template_time_savings group by team, template_name; - no such table: ts_template_time_savings type=errorHandler code=SQLITE_ERROR stack=SqliteError: SELECT sum(time_saved), team, template_name from ts_template_time_savings group by team, template_name; - no such table: ts_template_time_savings
[1]     at Database.prepare (/Users/jebentier/invoca/invoca-backstage/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
[1]     at Client_BetterSQLite3._query (/Users/jebentier/invoca/invoca-backstage/node_modules/knex/lib/dialects/better-sqlite3/index.js:35:34)
[1]     at executeQuery (/Users/jebentier/invoca/invoca-backstage/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
[1]     at Client_BetterSQLite3.query (/Users/jebentier/invoca/invoca-backstage/node_modules/knex/lib/client.js:154:12)
[1]     at Runner.query (/Users/jebentier/invoca/invoca-backstage/node_modules/knex/lib/execution/runner.js:141:36)
[1]     at ensureConnectionCallback (/Users/jebentier/invoca/invoca-backstage/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
[1]     at Runner.ensureConnection (/Users/jebentier/invoca/invoca-backstage/node_modules/knex/lib/execution/runner.js:318:20)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async Runner.run (/Users/jebentier/invoca/invoca-backstage/node_modules/knex/lib/execution/runner.js:30:19)
[1]     at DatabaseOperations.getAllStats (/Users/jebentier/invoca/invoca-backstage/node_modules/@tduniec/backstage-plugin-time-saver-backend/src/database/databaseOperations.ts:157:22)
[1]     at TsApi.getAllStats (/Users/jebentier/invoca/invoca-backstage/node_modules/@tduniec/backstage-plugin-time-saver-backend/src/api/apiService.ts:66:25)
[1]     at <anonymous> (/Users/jebentier/invoca/invoca-backstage/node_modules/@tduniec/backstage-plugin-time-saver-backend/src/service/router.ts:89:16)
```

When I look at the `packages/backend/db/timesaver.sqlite`, I can see that the `init.js` was flagged as having run successfully:
<img width="1335" alt="image" src="https://github.com/tduniec/backstage-timesaver-plugin/assets/571077/70238794-1dd6-4dbb-aca2-5df14d499d1e">

I'm currently running with the following package versions installed:

`@tduniec/backstage-plugin-time-saver-common`: `0.1.1`
`@tduniec/backstage-plugin-time-saver`: `0.1.6`
`@tduniec/backstage-plugin-time-saver-backend`: `0.1.7`

Any help is greatly appreciated, this plugin will be very useful in getting ROI data on our Backstage implementation.

**Comment by tduniec** [comment]
Hey,

thanks for interest in this plugin!
Unfortunatelly I haven’t prepared plugin to work with SQLite, it is required to set it up on postgres. 

Can you check with postgresDB and let me know ?

**Comment by jebentier** [comment]
Ah, thanks I didn't realize this only worked with a postgresql database. I can confirm that it works on postgresql. I'm curious what the issue is with getting the database working with SQlite? I see that there is a default being set on the `id` field, but I've never seen that done for any other plugin database.

**Comment by tduniec** [comment]
Yes, I will include this also to work on SQLite since I can see the demand is bigger than expected. :) 

I hole you like the plugin, Feedback is more than welcomed :)

**Comment by jebentier** [comment]
🤔 I know this isn't related to the original issue, but I'm now getting an error on page load when attempting to use `postgres`. The error is `theme.applyStyles is not a function`

**Comment by toma2395** [comment]
Hey, 

please take a look here: 
https://github.com/tduniec/backstage-timesaver-plugin/issues/3#issuecomment-1952562814

This issue should be covered here

**Comment by jebentier** [comment]
Thank you for the quick response. I did find a fix for it that didn't require blowing away my entire `yarn.lock`, which was to run `yarn upgrade-interactive` in order to force all installations of `@backstage/theme` to the latest `0.5.0` version. The plugin is now successfully loading the UI. Thank you for the help with this.

**Comment by jebentier** [comment]
Thank you very much for all the helpfulness here, I really appreciate it. I'm currently trying to run the `migrate` action through the API so that previously run tasks can be imported into the time savings database, and I'm getting the following error:

```
Error selecting data:
            select spec from scaffolder.tasks where id=$1
             - relation \"scaffolder.tasks\" does not exist
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

Have y'all seen this before?

**Comment by toma2395** [comment]
I see where the issue is, let me fix that for such use case.

**Comment by toma2395** [comment]
Can you test this version of plugin ? 
https://www.npmjs.com/package/@tduniec/backstage-plugin-time-saver-backend/v/0.1.8-0

**Comment by jebentier** [comment]
@toma2395 That's worked! Thank you so much for the quick fix here!

**Comment by toma2395** [comment]
Can we close the issue ? 
I will be adding this to patch package soon

**Comment by jebentier** [comment]
Yea we can go ahead and close the issue and track SQlite support separately. Thank you for all the help on this.
